version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    environment:
      SKIP_CHOWN: "true"
      SKIP_SETCAP: "true"
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 1
            }
          },
          "ui": true,
          "disable_mlock": true
        }
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/file

volumes:
  vault-data:
